services:
  # Servicio Web para la aplicación Laravel (PHP)
  - type: web
    name: portfolio-alumnos
    env: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_URL
        # Asegúrate de que esta URL coincida con la de tu servicio en Render
        value: https://portfolio-alumnos.onrender.com 
      - key: APP_KEY
        # Pega aquí la clave que generaste con 'php artisan key:generate --show'
        generateValue: true 
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: internalConnectionString

  # Servicio de Base de Datos PostgreSQL
  - type: postgres # <-- CORREGIDO DE 'psql' a 'postgres'
    name: portfolio-db
    plan: free