# Define los servicios y la base de datos para Render

# Primero, define la base de datos
databases:
  - name: portfolio-db
    plan: free # Usa el plan gratuito

# Luego, define los servicios que usarán la base de datos
services:
  # Servicio Web para la aplicación Laravel (PHP)
  - type: web
    name: portfolio-alumnos
    env: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_URL
        # Render asignará esta URL automáticamente
        fromService:
          type: web
          name: portfolio-alumnos
          property: url
      - key: APP_KEY
        # Genera una clave segura automáticamente
        generateValue: true 
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        # Toma la URL de conexión de la base de datos definida arriba
        fromDatabase:
          name: portfolio-db
          property: internalConnectionString
