databases:
  - name: portfolio-db
    plan: free

services:
  - type: web
    name: portfolio-alumnos
    plan: free
    env: docker # ¡Le decimos a Render que use Docker!
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: portfolio-alumnos
          property: url
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
